image_width: 1280
image_height: 1024
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1318.92993,    0.     ,  670.07096,
            0.     , 1329.67417,  373.32159,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.299629, 0.320112, -0.023601, 0.003170, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1249.38806,    0.     ,  674.78836,    0.     ,
            0.     , 1240.56909,  349.01162,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
