# image_width: 1440
# image_height: 1080
# camera_name: narrow_stereo
# camera_matrix:
#   rows: 3
#   cols: 3
#   data: [2336.69829,    0.     ,  708.52593,
#             0.     , 2342.80034,  546.97835,
#             0.     ,    0.     ,    1.     ]
# distortion_model: plumb_bob
# distortion_coefficients:
#   rows: 1
#   cols: 5
#   data: [-0.073231, 0.225358, -0.001236, -0.000111, 0.000000]
# rectification_matrix:
#   rows: 3
#   cols: 3
#   data: [1., 0., 0.,
#          0., 1., 0.,
#          0., 0., 1.]
# projection_matrix:
#   rows: 3
#   cols: 4
#   data: [2323.60913,    0.     ,  707.89502,    0.     ,
#             0.     , 2333.01514,  546.0421 ,    0.     ,
#             0.     ,    0.     ,    1.     ,    0.     ]
# hik_camera 8mm
image_width: 1440
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1803.85723,    0.     ,  698.29467,
            0.     , 1800.27952,  579.92966,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.086982, 0.202748, -0.000254, 0.000123, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1787.40894,    0.     ,  697.99599,    0.     ,
            0.     , 1787.37134,  579.63274,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]


# #舵轮
# image_width: 1280
# image_height: 1024
# camera_name: narrow_stereo
# camera_matrix:
#   rows: 3
#   cols: 3
#   data: [1572.88211,    0.     ,  593.60778,
#             0.     , 1577.08106,  537.61906,
#             0.     ,    0.     ,    1.     ]
# distortion_model: plumb_bob
# distortion_coefficients:
#   rows: 1
#   cols: 5
#   data: [-0.071926, 0.238979, -0.003171, -0.001378, 0.000000]
# rectification_matrix:
#   rows: 3
#   cols: 3
#   data: [1., 0., 0.,
#          0., 1., 0.,
#          0., 0., 1.]
# projection_matrix:
#   rows: 3
#   cols: 4
#   data: [1572.99023,    0.     ,  592.78148,    0.     ,
#             0.     , 1573.77161,  534.27836,    0.     ,
#             0.     ,    0.     ,    1.     ,    0.     ]


# #hik 6mm

# image_width: 1440
# image_height: 1080
# camera_name: narrow_stereo
# camera_matrix:
#   rows: 3
#   cols: 3
#   data: [1845.90808,    0.     ,  680.89014,
#             0.     , 1844.64913,  539.98111,
#             0.     ,    0.     ,    1.     ]
# distortion_model: plumb_bob
# distortion_coefficients:
#   rows: 1
#   cols: 5
#   data: [-0.053735, 0.196743, -0.002176, -0.008282, 0.000000]
# rectification_matrix:
#   rows: 3
#   cols: 3
#   data: [1., 0., 0.,
#          0., 1., 0.,
#          0., 0., 1.]
# projection_matrix:
#   rows: 3
#   cols: 4
#   data: [1841.89026,    0.     ,  672.75216,    0.     ,
#             0.     , 1849.77026,  537.93922,    0.     ,
#             0.     ,    0.     ,    1.     ,    0.     ]


# #hik 12mm

# image_width: 1440
# image_height: 1080
# camera_name: narrow_stereo
# camera_matrix:
#   rows: 3
#   cols: 3
#   data: [3690.55833,    0.     ,  752.00667,
#             0.     , 3695.35678,  603.06531,
#             0.     ,    0.     ,    1.     ]
# distortion_model: plumb_bob
# distortion_coefficients:
#   rows: 1
#   cols: 5
#   data: [-0.171130, 0.703344, 0.002852, 0.005804, 0.000000]
# rectification_matrix:
#   rows: 3
#   cols: 3
#   data: [1., 0., 0.,
#          0., 1., 0.,
#          0., 0., 1.]
# projection_matrix:
#   rows: 3
#   cols: 4
#   data: [3666.48657,    0.     ,  754.27216,    0.     ,
#             0.     , 3678.94116,  603.57042,    0.     ,
#             0.     ,    0.     ,    1.     ,    0.     ]