image_width: 1280
image_height: 1024
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [2104.16418,    0.     ,  642.28246,
            0.     , 2101.11252,  493.3795 ,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.074210, 0.625746, 0.002530, -0.000312, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2112.52344,    0.     ,  641.51796,    0.     ,
            0.     , 2106.31689,  494.5396 ,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
